import React from 'react';
import CropCard from './CropCard';

const CropsPage = () => {
  const crops = [
    {
      name: 'Maize',
      category: 'Food crop',
      description: 'Maize, Zea mays, is an annual grass in the family Poaceae and is a staple food crop grown all over the world. The maize plant possesses a simple stem of nodes and internodes.',
      requirements: 'Maize is best grown in warm, tropical and sub-tropical regions as it requires warm soils to develop optimally. One of the most important requirements for growing maize is a high quality soil which is deep, fertile and well-draining with a pH between 6.0 and 6.8. Maize plants are very heavy feeders and even the most fertile of soils may need to supplemented with nutrients as the plants develop, particularly nitrogen. Maize also requires plenty of space as it grows and is pollinated by wind. It should be planted where it will receive full sunlight for most of the day and provided with ample moisture.',
      planting: 'Planting dates for maize depend on the variety being grown. Standard varieties should be planted when the soil has warmed to at least 12.7°C (55°F) and supersweet varieties when the soil reaches 18.3°C (65°F). Soil can be brought up to temperature faster by laying black plastic mulches approximately 1 week prior to planting. Seeds should be sown about 2.5 cm (1 in) deep and 10–15 cm (~3–4 in) apart allowing 76–91 cm (~30–36 in) between rows. Maize should be planted in blocks (numerous rows) rather than in a single long row as it is wind pollinated and pollen can transfer between plants much more efficiently. Seedlings should be thinned to a final spacing 20–30 cm (8–12 in) when they are approximately 7.5–10.0 cm (3–4 in) in height. It is common to stagger maize plantings to ensure a continuous harvest over the summer months.',
      care_and_maintenance: 'Maize plants are heavy feeders, particularly of nitrogen (N) and care should be taken to provide them with adequate nutrients by applying fertilizer. Maize undergoes a rapid growth period between 30 and 40 days after planting and should be fertilized just before this. All fertilizer applications should be made before the tasseling period to ensure the plant maximizes nitrogen use. Be aware of symptoms of nutrient deficiency, plants should be a deep green color. Purple tinged leaves indicate that the plants are suffering from a lack of phosphorous, whereas light green leaves indicate a lack of nitrogen. Apply fertilizer. Plants also require adequate soil moisture throughout the growing period in order to tassel and form silks. Soaker hoses can be used to great effect in small to mid-size plantings. Pollination occurs when pollen is transferred from the male tassel to the female silk by the wind. Each silk produced a single kernel of corn and partially filled ears are usually a result of poor pollination.',
      uses: 'Maize and cornmeal (dried, ground maize) are staple foods in countries all over the world. The ears can be cooked and eaten from the cob as a vegetable or the kernels can be removed and either eaten as is or used to produce a wide variety of foodstuffs including cereals and flour. Maize is also a major source of starch, which can be processed into oils and high fructose corn syrup. Maize is also commonly grown as feed for livestock.',
      Harvesting: 'Each maize stalk should produce 1 large ear of maize. Under ideal conditions, the stalk will produce a second, slightly smaller ear which reaches maturity slightly later than the first. Maize ears should be harvested at the “milk stage” of development, when the kernels within the husk are well packed and produce a milky substance when the kernel is punctured. Check ears for ripeness by gently peeling back a small portion of the husk. Be sure to check the ears frequently for ripeness and harvest as required as ears can quickly become over-ripe and lose their sweetness. Remove the ears from the stalk by pulling quickly downward while twisting and then refrigerate until consumption.',
      image: 'https://s3.amazonaws.com/plantvillage-production-new/images/pics/000/002/330/original/4022961158_c32960eba9_z.jpg?1392393913'
    },
    {
      name: 'Avocado',
      category: 'Food crop',
      description: 'Maize, Zea mays, is an annual grass in the family Poaceae and is a staple food crop grown all over the world. The maize plant possesses a simple stem of nodes and internodes.',
      requirements: 'Maize is best grown in warm, tropical and sub-tropical regions as it requires warm soils to develop optimally. One of the most important requirements for growing maize is a high quality soil which is deep, fertile and well-draining with a pH between 6.0 and 6.8. Maize plants are very heavy feeders and even the most fertile of soils may need to supplemented with nutrients as the plants develop, particularly nitrogen. Maize also requires plenty of space as it grows and is pollinated by wind. It should be planted where it will receive full sunlight for most of the day and provided with ample moisture.',
      planting: 'Planting dates for maize depend on the variety being grown. Standard varieties should be planted when the soil has warmed to at least 12.7°C (55°F) and supersweet varieties when the soil reaches 18.3°C (65°F). Soil can be brought up to temperature faster by laying black plastic mulches approximately 1 week prior to planting. Seeds should be sown about 2.5 cm (1 in) deep and 10–15 cm (~3–4 in) apart allowing 76–91 cm (~30–36 in) between rows. Maize should be planted in blocks (numerous rows) rather than in a single long row as it is wind pollinated and pollen can transfer between plants much more efficiently. Seedlings should be thinned to a final spacing 20–30 cm (8–12 in) when they are approximately 7.5–10.0 cm (3–4 in) in height. It is common to stagger maize plantings to ensure a continuous harvest over the summer months.',
      care_and_maintenance: 'Maize plants are heavy feeders, particularly of nitrogen (N) and care should be taken to provide them with adequate nutrients by applying fertilizer. Maize undergoes a rapid growth period between 30 and 40 days after planting and should be fertilized just before this. All fertilizer applications should be made before the tasseling period to ensure the plant maximizes nitrogen use. Be aware of symptoms of nutrient deficiency, plants should be a deep green color. Purple tinged leaves indicate that the plants are suffering from a lack of phosphorous, whereas light green leaves indicate a lack of nitrogen. Apply fertilizer. Plants also require adequate soil moisture throughout the growing period in order to tassel and form silks. Soaker hoses can be used to great effect in small to mid-size plantings. Pollination occurs when pollen is transferred from the male tassel to the female silk by the wind. Each silk produced a single kernel of corn and partially filled ears are usually a result of poor pollination.',
      uses: 'Maize and cornmeal (dried, ground maize) are staple foods in countries all over the world. The ears can be cooked and eaten from the cob as a vegetable or the kernels can be removed and either eaten as is or used to produce a wide variety of foodstuffs including cereals and flour. Maize is also a major source of starch, which can be processed into oils and high fructose corn syrup. Maize is also commonly grown as feed for livestock.',
      Harvesting: 'Each maize stalk should produce 1 large ear of maize. Under ideal conditions, the stalk will produce a second, slightly smaller ear which reaches maturity slightly later than the first. Maize ears should be harvested at the “milk stage” of development, when the kernels within the husk are well packed and produce a milky substance when the kernel is punctured. Check ears for ripeness by gently peeling back a small portion of the husk. Be sure to check the ears frequently for ripeness and harvest as required as ears can quickly become over-ripe and lose their sweetness. Remove the ears from the stalk by pulling quickly downward while twisting and then refrigerate until consumption.',
      image: 'https://s3.amazonaws.com/plantvillage-production-new/images/pics/000/003/350/original/3864733180_0499b2e86a_z.jpg?1411655691'
    },
    {
      name: 'Bean',
      category: 'Food crop',
      description: 'Maize, Zea mays, is an annual grass in the family Poaceae and is a staple food crop grown all over the world. The maize plant possesses a simple stem of nodes and internodes.',
      requirements: 'Maize is best grown in warm, tropical and sub-tropical regions as it requires warm soils to develop optimally. One of the most important requirements for growing maize is a high quality soil which is deep, fertile and well-draining with a pH between 6.0 and 6.8. Maize plants are very heavy feeders and even the most fertile of soils may need to supplemented with nutrients as the plants develop, particularly nitrogen. Maize also requires plenty of space as it grows and is pollinated by wind. It should be planted where it will receive full sunlight for most of the day and provided with ample moisture.',
      planting: 'Planting dates for maize depend on the variety being grown. Standard varieties should be planted when the soil has warmed to at least 12.7°C (55°F) and supersweet varieties when the soil reaches 18.3°C (65°F). Soil can be brought up to temperature faster by laying black plastic mulches approximately 1 week prior to planting. Seeds should be sown about 2.5 cm (1 in) deep and 10–15 cm (~3–4 in) apart allowing 76–91 cm (~30–36 in) between rows. Maize should be planted in blocks (numerous rows) rather than in a single long row as it is wind pollinated and pollen can transfer between plants much more efficiently. Seedlings should be thinned to a final spacing 20–30 cm (8–12 in) when they are approximately 7.5–10.0 cm (3–4 in) in height. It is common to stagger maize plantings to ensure a continuous harvest over the summer months.',
      care_and_maintenance: 'Maize plants are heavy feeders, particularly of nitrogen (N) and care should be taken to provide them with adequate nutrients by applying fertilizer. Maize undergoes a rapid growth period between 30 and 40 days after planting and should be fertilized just before this. All fertilizer applications should be made before the tasseling period to ensure the plant maximizes nitrogen use. Be aware of symptoms of nutrient deficiency, plants should be a deep green color. Purple tinged leaves indicate that the plants are suffering from a lack of phosphorous, whereas light green leaves indicate a lack of nitrogen. Apply fertilizer. Plants also require adequate soil moisture throughout the growing period in order to tassel and form silks. Soaker hoses can be used to great effect in small to mid-size plantings. Pollination occurs when pollen is transferred from the male tassel to the female silk by the wind. Each silk produced a single kernel of corn and partially filled ears are usually a result of poor pollination.',
      uses: 'Maize and cornmeal (dried, ground maize) are staple foods in countries all over the world. The ears can be cooked and eaten from the cob as a vegetable or the kernels can be removed and either eaten as is or used to produce a wide variety of foodstuffs including cereals and flour. Maize is also a major source of starch, which can be processed into oils and high fructose corn syrup. Maize is also commonly grown as feed for livestock.',
      Harvesting: 'Each maize stalk should produce 1 large ear of maize. Under ideal conditions, the stalk will produce a second, slightly smaller ear which reaches maturity slightly later than the first. Maize ears should be harvested at the “milk stage” of development, when the kernels within the husk are well packed and produce a milky substance when the kernel is punctured. Check ears for ripeness by gently peeling back a small portion of the husk. Be sure to check the ears frequently for ripeness and harvest as required as ears can quickly become over-ripe and lose their sweetness. Remove the ears from the stalk by pulling quickly downward while twisting and then refrigerate until consumption.',
      image: 'https://s3.amazonaws.com/plantvillage-production-new/images/pics/000/002/387/original/5027699128_fdd023b992_z.jpg?1392748749'
    },
  ]
  return (
    <div className="container mt-4">
      <div className="row">
        {
          crops.map((crop, key) => {
            return <div className="col-md-4" key={key}><CropCard crop={crop}/></div>
          })
        }
      </div>
    </div>
  )
}

export default CropsPage;

